
export const GET_TODO_REQUEST = "GET_TODO_REQUEST"
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS"
export const GET_TODO_FAILED = "GET_TODO_FAILED"


export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST"
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS"
export const ADD_TODO_FAILED = "ADD_TODO_FAILED"