export const PRODUCT_REQUEST = "PRODUCT_REQUEST"
export const PRODUCT_FAILURE = "PRODUCT_FAILURE"

//ADD PRODUCT
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"

// GET PRODUCT
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"

//PATCH PRODUCT
export const PATCH_PRODUCT_SUCCESS = "PATCH_PRODUCT_SUCCESS"